### ISSUE TITLE
Python Error when running on Windows

### ISSUE THREAD

**Issue by warrenspe** [mapproxy/mapproxy#1027]
First time using mapproxy, I'm trying to get a test site going but I'm getting an exception, which seems to be due to my running on windows:

## Context

```
Traceback (most recent call last):
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\wsgiapp.py", line 155, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\service\base.py", line 31, in handle
    return handler(parsed_req)
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\service\tile.py", line 81, in map
    tile = layer.render(tile_request, use_profiles=tile_request.use_profiles,
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\service\tile.py", line 314, in render
    tile = self.tile_manager.load_tile_coord(tile_coord,
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\cache\tile.py", line 122, in load_tile_coord
    return self.load_tile_coords(
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\cache\tile.py", line 151, in load_tile_coords
    tiles = self._load_tile_coords(
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\cache\tile.py", line 206, in _load_tile_coords
    created_tiles = creator.create_tiles(uncached_tiles)
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\cache\tile.py", line 373, in create_tiles
    created_tiles = self._create_single_tiles(tiles)
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\cache\tile.py", line 397, in _create_single_tiles
    created_tiles.extend(self._create_single_tile(tile))
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\cache\tile.py", line 411, in _create_single_tile
    with self.tile_mgr.lock(tile):
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\cache\tile.py", line 226, in lock
    return self.locker.lock(tile)
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\cache\base.py", line 118, in lock
    cleanup_lockdir(self.lock_dir, max_lock_time=self.lock_timeout + 10,
  File "C:\cdw\applications\workstation\install\venv\3_9\lib\site-packages\mapproxy\util\lock.py", line 119, in cleanup_lockdir
    if os.stat(name).st_uid == os.getuid():
AttributeError: module 'os' has no attribute 'getuid'
```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: 3.1.0
* Environment name and version (e.g. Python 3.8 with mod_wsgi 4.5.9): Python 3.9, waitress server
* Server type and version:
* Operating System and version: Windows 10

**Comment by simonseyock** [comment]
Thanks for reporting this! The offending line will be removed with https://github.com/mapproxy/mapproxy/pull/1025 anyways because the permission handling is then left to the OS anyways.
