### ISSUE TITLE
Layer Capabilities error

### ISSUE THREAD

**Issue by drnextgis** [mapproxy/mapproxy#156]
There is my simple config:

```
services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: metro4all
    title: Custom OSM style by trolleway
    sources: [metro4all_cache]

caches:
  metro4all_cache:
     grids: [webmercator]
     sources: [osm_metro4all]

sources:
  osm_metro4all:
    type: mapnik
    mapfile: /home/tenzorr/projects/osmlayer/src/metro4all-style/style.xml

grids:
    webmercator:
        base: GLOBAL_WEBMERCATOR
```

When I open demo service and click on link _click here_ in Layer Capabilities column of TMS layer - I get error:

```
internal error
```

Traceback:

```
[2014-07-11 15:10:49,526] mapproxy.wsgiapp - CRITICAL - fatal error in demo for /demo/ tms_capabilities&layer=osm&srs=EPSG3857
Traceback (most recent call last):
  File "/usr/home/tenzorr/projects/osmlayer/env/lib/python2.7/site-packages/mapproxy/wsgiapp.py", line 181, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "/usr/home/tenzorr/projects/osmlayer/env/lib/python2.7/site-packages/mapproxy/service/demo.py", line 105, in handle
    capabilities = urlopen(url)
  File "/usr/local/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by chengdi1988** [comment]
> Fixed in master.

I encountered this error again in my environment:
win10 64bit Chinese edition.
miniconda python 3.8.11
# install: 
```shell
pip install MapProxy pyproj
mapproxy-util --version # MapProxy 1.13.2
```

# configure:
```yaml
# -------------------------------
# MapProxy example configuration.
# -------------------------------
#
# This is a minimal MapProxy configuration.
# See full_example.yaml and the documentation for more options.
#

# Starts the following services:
# Demo:
#     http://localhost:8080/demo
# WMS:
#     capabilities: http://localhost:8080/service?REQUEST=GetCapabilities
# WMTS:
#     capabilities: http://localhost:8080/wmts/1.0.0/WMTSCapabilities.xml
#     first tile: http://localhost:8080/wmts/osm/webmercator/0/0/0.png
# Tile service (compatible with OSM/etc.)
#     first tile: http://localhost:8080/tiles/osm/webmercator/0/0/0.png
# TMS:
#     note: TMS is not compatible with OSM/Google Maps/etc.
#     first tile: http://localhost:8080/tms/1.0.0/osm/webmercator/0/0/0.png
# KML:
#     initial doc: http://localhost:8080/kml/osm/webmercator

services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: osm
    title: Omniscale OSM WMS - osm.omniscale.net
    sources: [osm_cache]
  - name: gggis_sat
    title: GGGIS-sat - 卫星影像
    sources: [gggis_sat_cache]
  - name: gggis_sat_cn
    title: GGGIS-sat-cn - 卫星影像(中文标注)
    sources: [gggis_sat_cn_cache]
  - name: gggis_terrain_cn
    title: GGGIS-terrain-cn - 地形(中文标注)
    sources: [gggis_terrain_cn_cache]

caches:
  osm_cache:
    grids: [webmercator]
    sources: [osm_wms]
    cache:
      type: geopackage
      levels: true
  gggis_sat_cache:
    grids: [webmercator]
    sources: [gggis_sat_tile]
    cache:
      type: geopackage
      levels: true
  gggis_sat_cn_cache:
    grids: [webmercator]
    sources: [gggis_sat_cn_tile]
    cache:
      type: geopackage
      levels: true
  gggis_terrain_cn_cache:
    grids: [webmercator]
    sources: [gggis_terrain_cn_tile]
    cache:
      type: geopackage
      levels: true
sources:
  osm_wms:
    type: wms
    req:
      url: https://maps.omniscale.net/v2/demo/style.default/service?
      layers: osm
  gggis_sat_tile: # gggis 是googlemap的镜像，所以是tiles而不是tms
    type: tile
    url: http://****.amap.icu/vt/lyrs=s&x=%(x)s&y=%(y)s&z=%(z)s
    grid: webmercator # 原点在西北
  gggis_sat_cn_tile: # gggis 是googlemap的镜像，所以是tiles而不是tms
    type: tile
    url: http://****.amap.icu/vt/lyrs=y&x=%(x)s&y=%(y)s&z=%(z)s
    grid: webmercator # 原点在西北
  gggis_terrain_cn_tile: # gggis 是googlemap的镜像，所以是tiles而不是tms
    type: tile
    url: http://****.amap.icu/vt/lyrs=p&x=%(x)s&y=%(y)s&z=%(z)s
    grid: webmercator # 原点在西北

grids:
    webmercator:
        base: GLOBAL_WEBMERCATOR # ESPG 3857

globals:

```
# The errors:
```
[2021-09-30 20:55:26,478] mapproxy.wsgiapp - CRITICAL - fatal error in demo for /demo/?tms_capabilities
Traceback (most recent call last):
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 951, in send
    self.connect()
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 922, in connect
    self.sock = self._create_connection(
  File "c:\users\n2o\.conda\envs\test\lib\socket.py", line 808, in create_connection
    raise err
  File "c:\users\n2o\.conda\envs\test\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\n2o\.conda\envs\test\lib\site-packages\mapproxy\wsgiapp.py", line 141, in __call__      
    resp = self.handlers[handler_name].handle(req)
  File "c:\users\n2o\.conda\envs\test\lib\site-packages\mapproxy\service\demo.py", line 123, in handle   
    capabilities = urllib2.urlopen(internal_url)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10049] 在其上下文中，该请求的地址无效。>
Traceback (most recent call last):
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 951, in send
    self.connect()
  File "c:\users\n2o\.conda\envs\test\lib\http\client.py", line 922, in connect
    self.sock = self._create_connection(
  File "c:\users\n2o\.conda\envs\test\lib\socket.py", line 808, in create_connection
    raise err
  File "c:\users\n2o\.conda\envs\test\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\n2o\.conda\envs\test\lib\site-packages\mapproxy\wsgiapp.py", line 141, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "c:\users\n2o\.conda\envs\test\lib\site-packages\mapproxy\service\demo.py", line 123, in handle   
    capabilities = urllib2.urlopen(internal_url)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\users\n2o\.conda\envs\test\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10049] 在其上下文中，该请求的地址无效。>
```

# [WinError 10049] 
I looked into it. It may be related to how I launch the development server:
```shell
mapproxy-util serve-develop -b :1234 mapproxy.yaml # with only port and omit the ip address.
```

if I launch it with complete ip address and port
```shell
mapproxy-util serve-develop -b localhost:1234 mapproxy.yaml 
```

This WinError 10049 disappears .-)
