### ISSUE TITLE
Ability to specify URL GET parameters for tile source

### ISSUE THREAD

**Issue by shr3k** [mapproxy/mapproxy#172]
Hello, it would be nice to have possibility specify some GET parameters for tile source, like
url: http://myarcgis/ArcGIS/rest/services/mylayer/MapServer/tile/%(z)s/%(y)s/%(x)s?token=mytoken

Currently it ends with:
```
...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/wsgiapp.py", line 166, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/service/base.py", line 30, in handle
    return handler(parsed_req)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/service/tile.py", line 81, in map
    tile = layer.render(tile_request, use_profiles=tile_request.use_profiles, coverage=limit_to, decorate_img=decorate_img)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/service/tile.py", line 307, in render
    dimensions=dimensions, with_metadata=True)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 106, in load_tile_coord
    created_tiles = creator.create_tiles([tile])
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 229, in create_tiles
    created_tiles = self._create_meta_tiles(meta_tiles)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 302, in _create_meta_tiles
    created_tiles.extend(self._create_meta_tile(meta_tile))
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 312, in _create_meta_tile
    meta_tile_image = self._query_sources(query)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 276, in _query_sources
    return self.sources[0].get_map(query)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/source/tile.py", line 95, in get_map
    return CacheMapLayer.get_map(self, query)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/layer.py", line 425, in get_map
    result = self._image(query)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/layer.py", line 458, in _image
    tile_collection = self.tile_manager.load_tile_coords(affected_tile_coords, with_metadata=query.tiled_only)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 127, in load_tile_coords
    created_tiles = creator.create_tiles(uncached_tiles)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 215, in create_tiles
    created_tiles = self._create_single_tiles(tiles)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 235, in _create_single_tiles
    return self._create_threaded(self._create_single_tile, tiles)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 245, in _create_threaded
    for new_tiles in async_pool.imap(create_func, tiles):
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/util/async.py", line 54, in _result_iter
    for result in results:
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/util/async.py", line 191, in map_each
    for value in self._get_results(next_result, results, raise_exceptions):
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/util/async.py", line 235, in _get_results
    for i, value in self._fetch_results(raise_exceptions):
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/util/async.py", line 144, in run
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 255, in _create_single_tile
    source = self._query_sources(query)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 276, in _query_sources
    return self.sources[0].get_map(query)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/source/tile.py", line 75, in get_map
    return self.client.get_tile(tile_coord, format=query.format)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/client/tile.py", line 42, in get_tile
    url = self.url_template.substitute(tile_coord, format, self.grid)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/client/tile.py", line 98, in substitute
    return self.template % data
TypeError: not enough arguments for format string
```

**Comment by shr3k** [comment]
Oliver, mea culpa, can be closed, as works url: 'http://myarcgis/ArcGIS/rest/services/mylayer/MapServer/tile/%(z)s/%(y)s/%(x)s?token=mytoken' (with single quotes)

**Comment by valdezm** [comment]
What about sending a custom CQL filter parameter?
