### ISSUE TITLE
Crash if using a tile source with https://

### ISSUE THREAD

**Issue by IvanSanchez** [mapproxy/mapproxy#176]
I'm using mapproxy to cache mapbox tiles (locally, for development purposes). Setting a tile source like this works fine:

```
sources:
  mapbox_source:
    type: tile
    url: http://a.tiles.mapbox.com/v3/mazemap.supersecretapikey/%(z)s/%(x)s/%(y)s.png
    grid: osm_grid
```

But using ```https://``` instead of ```http://``` for the tile source URL makes mapproxy crash with the following error message:

```
[info]  * Detected change in '/home/ivan/mapproxy/mapproxy.yaml', reloading
[info]  * Restarting with reloader: stat() polling
Traceback (most recent call last):
  File "/usr/local/bin/mapproxy-util", line 9, in <module>
    load_entry_point('MapProxy==1.7.1', 'console_scripts', 'mapproxy-util')()
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/script/util.py", line 362, in main
    commands[command]['func'](args)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/script/util.py", line 81, in serve_develop_command
    app = make_wsgi_app(mapproxy_conf, debug=options.debug)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/wsgiapp.py", line 105, in make_wsgi_app
    services = conf.configured_services()
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/config/loader.py", line 208, in configured_services
    return self.services.services()
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/config/loader.py", line 1432, in services
    new_services = creator(service_conf or {})
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/config/loader.py", line 1576, in demo_service
    layers[layer_name] = layer_conf.wms_layer()
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/util/py.py", line 62, in wrapper
    cache[args] = func(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/config/loader.py", line 1300, in wms_layer
    map_layer = self.context.caches[source_name].map_layer()
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/util/py.py", line 62, in wrapper
    cache[args] = func(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/config/loader.py", line 1232, in map_layer
    for grid, extent, tile_manager in self.caches():
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/util/py.py", line 62, in wrapper
    cache[args] = func(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/config/loader.py", line 1153, in caches
    source = source_conf.source({'format': request_format})
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/config/loader.py", line 855, in source
    http_client, url = self.http_client(url)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/config/loader.py", line 560, in http_client
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/mapproxy/client/http.py", line 118, in __init__
    raise HTTPClientError('No ca_certs file set (http.ssl_ca_certs). '
mapproxy.client.http.HTTPClientError: No ca_certs file set (http.ssl_ca_certs). Set file or disable verification with http.ssl_no_cert_checks option.
```

I'm not sure if I'm missing some python config/package for the CA certs, or if it should be a good idea to allow overriding SSL checks in the ```mapproxy.yaml``` config file.

**Comment by olt** [comment]
You can disable SSL checking or provide a CA certs file. Either in `globals.http` or in the `http` section of the source. See http://mapproxy.org/docs/nightly/configuration.html#secure-https-connections-https

**Comment by ChameleonScales** [comment]
Hi,
Sorry I'm lost here.
How do you disable SSL checking ?

**Comment by bor8** [comment]
For the googlers:

Example:

```
sources:
  ***_wms:
    type: wms
    wms_opts:
      # just query feature informations and no map
      featureinfo: true
    req:
      url: https://***?
      layers: 0
      transparent: true
    http:
      ssl_no_cert_checks: true
```
