### ISSUE TITLE
UnicodeDecodeError with coverage from shapefiles

### ISSUE THREAD

**Issue by ramunasd** [mapproxy/mapproxy#211]
I'm trying to run mapproxy-seed with coverage from shapefiles.

Python version is 3.4.3

No problems with same configuration in 2.7.x

```
Traceback (most recent call last):
  File "/root/mapproxy_3/bin/mapproxy-seed", line 11, in <module>
    sys.exit(main())
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/seed/script.py", line 248, in main
    return SeedScript()()
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/seed/script.py", line 140, in __call__
    seed_tasks = seed_conf.seeds(seed_names)
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/seed/config.py", line 201, in seeds
    seed_conf = SeedConfiguration(seed_name, seed_conf, self)
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/seed/config.py", line 282, in __init__
    ConfigurationBase.__init__(self, name, conf, seeding_conf)
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/seed/config.py", line 228, in __init__
    self.coverage = self._coverages()
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/seed/config.py", line 237, in _coverages
    coverages = [self.seeding_conf.coverage(c) for c in self.conf.get('coverages', {})]
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/seed/config.py", line 237, in <listcomp>
    coverages = [self.seeding_conf.coverage(c) for c in self.conf.get('coverages', {})]
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/util/py.py", line 78, in wrapper
    cache[args] = func(self, *args)
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/seed/config.py", line 153, in coverage
    coverage = load_coverage(coverage_conf)
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/config/coverage.py", line 71, in load_coverage
    geom = load_datasource(datasource, where)
  File "/root/mapproxy_3/local/lib/python3.4/site-packages/mapproxy/util/geom.py", line 61, in load_datasource
    data = fp.read(50)
  File "/root/mapproxy_3/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 28: invalid continuation byte
```

**Comment by rightway1** [comment]
I am seeing the same error with shapefile coverages, including shapefiles that have worked in older versions of MapProxy & Python.

I'm using Python 3.4.4 and MapProxy 1.8.2.  Shapely 1.5.15 and GEOS 3.4.2 are also installed, but the code seems to be failing in geom.py when it just tries to read the file using a standard file reader.  
Perhaps the most flexible approach would be to catch the error and  continue on to try the load_ogr_datasource instead?
