### ISSUE TITLE
mapproxy-util scales --as-res-config doesn't work on python 3

### ISSUE THREAD

**Issue by tudorbarascu** [mapproxy/mapproxy#218]
Hi and thank you for your nice work.

Running 
```
mapproxy-util scales --as-res-config 559082264.0285016 279541132.0142503
```
works only under Python 2.7.

Under 3.4.4 at least I get:
```
Traceback (most recent call last):
  File "/venv_mapproxy/bin/mapproxy-util", line 11, in <module>
    sys.exit(main())
  File "/venv_mapproxy/lib/python3.4/site-packages/mapproxy/script/util.py", line 365, in main
    commands[command]['func'](args)
  File "/venv_mapproxy/lib/python3.4/site-packages/mapproxy/script/scales.py", line 98, in scales_command
    values.sort(reverse=True)
AttributeError: 'map' object has no attribute 'sort'
```

**Comment by olt** [comment]
Thanks for the report.
