### ISSUE TITLE
MBTile cache error when seeding with multiprocessing

### ISSUE THREAD

**Issue by palmerj** [mapproxy/mapproxy#280]
When seeding tiles e.g:

```
mapproxy-seed -f maptiles.yml -s seeds.yml -c 8
```

from a mapnik source to an mbtiles cache I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/MapProxy-1.10.0a0.post20161201-py2.7.egg/mapproxy/seed/seeder.py", line 167, in run
    self.work_loop()
  File "/usr/local/lib/python2.7/dist-packages/MapProxy-1.10.0a0.post20161201-py2.7.egg/mapproxy/seed/seeder.py", line 182, in work_loop
    exceptions=(SourceError, IOError), ignore_exceptions=(LockTimeout, ))
  File "/usr/local/lib/python2.7/dist-packages/MapProxy-1.10.0a0.post20161201-py2.7.egg/mapproxy/seed/util.py", line 226, in exp_backoff
    result = func(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/MapProxy-1.10.0a0.post20161201-py2.7.egg/mapproxy/cache/tile.py", line 127, in load_tile_coords
    self.cache.load_tiles(tiles, with_metadata)
  File "/usr/local/lib/python2.7/dist-packages/MapProxy-1.10.0a0.post20161201-py2.7.egg/mapproxy/cache/mbtiles.py", line 239, in load_tiles
    cursor.execute(stmt, cur_coords)
DatabaseError: file is encrypted or is not a database
```

This doesn't seem to happen when I use a lower number of processes. e.g 4

Note: The mbtile database was created at the start of this seeding process and was not initially created by another process.

**Comment by olt** [comment]
Locking errors can happen at high load, but `file is encrypted or is not a database` means the database is corrupted.
This is likely out of the scope of MapProxy (network storage?)
