### ISSUE TITLE
Missing __init__.py file

### ISSUE THREAD

**Issue by drnextgis** [mapproxy/mapproxy#314]
I'm trying to deploy MapProxy installed in virtualenv with system-wide gunicorn. For this purpose I've added the following option to gunicorn config:

```
CONFIG = {
    'environment': {
        'PYTHONPATH': '/home/dr/ngw/env/lib/python2.7/site-packages',
    },
    ...
}
```

But in this case I get an error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 473, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/geventlet.py", line 30, in init_process
    super(EventletWorker, self).init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 115, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 33, in load
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 362, in import_app
    __import__(module)
  File "/home/dr/ngw/mapproxy/config.py", line 9, in <module>
    from mapproxy.wsgiapp import make_wsgi_app
ImportError: No module named mapproxy.wsgiapp
```

It happens because `mapproxy` package doesn't contain `__init__.py` file. If add it manually all works fine.

**Comment by drnextgis** [comment]
Oops, it looks like duplicate of https://github.com/mapproxy/mapproxy/issues/310
