### ISSUE TITLE
Demo service does not respect `use_grid_names`

### ISSUE THREAD

**Issue by arigesher** [mapproxy/mapproxy#317]
## Context

When using a service that uses grid names, loading up the demo service yields blank maps.

## Expected Behavior

The grid name flag should be respected by the demo service and used properly in the generated javascript.

## Actual Behavior

Grid name is ignored, in favor of CRS.  Not only are no tiles shown, but clicking on the capabilities link yields this stack trace:

```
[info] 127.0.0.1 - - [28/Jun/2017 17:40:14] "GET /tms/1.0.0/terrain_map/EPSG3857 HTTP/1.1" 404 -
Traceback (most recent call last):
  File "/Users/regs/.virtualenv/r2ch4/lib/python3.5/site-packages/mapproxy/wsgiapp.py", line 189, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "/Users/regs/.virtualenv/r2ch4/lib/python3.5/site-packages/mapproxy/service/demo.py", line 114, in handle
    capabilities = urllib2.urlopen(url)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[info] 127.0.0.1 - - [28/Jun/2017 17:40:14] "GET /demo/?tms_capabilities&layer=terrain_map&srs=EPSG3857 HTTP/1.1" 500
```

*Full output:* [test_server_output.txt](https://github.com/mapproxy/mapproxy/files/1111049/test_server_output.txt)

## Possible Fix

I was able to relate this behavior to a bug in the generated JavaScript that appeared to not be respecting the `use_grid_names` parameter. It's unclear if they have some root cause.

_**Note that this behavior is new in 1.10; 1.9.1 does not exhibit this behavior**._

## Steps to Reproduce
0. mkdir -p /opt/kairos/cache/tiles
1. `mapproxy-seed -s [mapproxy-seeds.yml.txt][1] -c 32 -f [mapproxy-service.yml.txt][2] --seed=ALL`
2. `mapproxy-util serve-develop [mapproxy-service.yml.txt][2]`
3. load demo application: [http://localhost:8080/demo/?tms_layer=terrain_map&format=png&srs=EPSG%3A3857][3]
4. Observe above stacktrace in console and output `internal error` in browser.

 
[1]: https://github.com/mapproxy/mapproxy/files/1111032/mapproxy-seeds.yml.txt
[2]: https://github.com/mapproxy/mapproxy/files/1111031/mapproxy-service.yml.txt
[3]: http://localhost:8080/demo/?tms_layer=terrain_map&format=png&srs=EPSG%3A3857

## Context

Testing the tile service after seeding.

## Your Environment
* Version used: 1.10.2
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 3.5.2 (python.org) `mapproxy-utils serve-develop`
* Server type and version: Macbook Pro
* Operating System and version: OS X 10.12

**Comment by drnextgis** [comment]
@arigesher, fix has landed in master branch.

**Comment by skipjack** [comment]
I'm seeing this issue again on the latest release... when `use_grid_names: true` is included in the `tms` service, the map comes up blank (and if you open the console you can see the failed requests).

Could we reopen or should I create a new issue?

**Comment by olt** [comment]
There is no release yet that contains this fix.

**Comment by skipjack** [comment]
Ah I see, didn't realize it was so recent.
