### ISSUE TITLE
Confusing error message for mapproxy-seed and invalid configuration files

### ISSUE THREAD

**Issue by pnorman** [mapproxy/mapproxy#352]
I was passing mapproxy-seed the wrong file for `-f`, and got this error message

```
Traceback (most recent call last):
  File "mapproxy/bin/mapproxy-seed", line 11, in <module>
    sys.exit(main())
  File "/home/pnorman/lz-prerender/mapproxy/local/lib/python2.7/site-packages/mapproxy/seed/script.py", line 361, in main
    return SeedScript()()
  File "/home/pnorman/lz-prerender/mapproxy/local/lib/python2.7/site-packages/mapproxy/seed/script.py", line 178, in __call__
    mapproxy_conf = load_configuration(options.conf_file, seed=True)
  File "/home/pnorman/lz-prerender/mapproxy/local/lib/python2.7/site-packages/mapproxy/config/loader.py", line 1972, in load_configuration
    conf_dict = load_configuration_file([os.path.basename(mapproxy_conf)], conf_base_dir)
  File "/home/pnorman/lz-prerender/mapproxy/local/lib/python2.7/site-packages/mapproxy/config/loader.py", line 2004, in load_configuration_file
    base_files = current_dict.pop('base')
AttributeError: 'str' object has no attribute 'pop'
```

It should be possible to catch this message and return a more user-friendly error.

**Comment by olt** [comment]
Thanks for reporting this!
