### ISSUE TITLE
coverages with OGR datasoure and where clause for text columns

### ISSUE THREAD

**Issue by Pocho737** [mapproxy/mapproxy#360]
If, according to Documentation, a source is limited to an OGR datasource including a where clause/SQL statement referring to a non-integer column (text/varchar), mapproxy fails.
## Context

Mapproxy supports

> Any polygon datasource that is supported by OGR (e.g. Shapefile, GeoJSON, PostGIS).
> Restrict which polygons should be loaded from the datasource. Either a simple where statement (e.g. 'CNTRY_NAME="Germany"') or a full select statement. 

Since GDAL 2.0 strict SQL 92 rules (SQL quoting) are in force [http://www.gdal.org/ogr_sql.html#ogr_sql_quot](http://www.gdal.org/ogr_sql.html#ogr_sql_quot)

> String literals (constants) must be surrounded with single-quote characters. e.g. WHERE a_field = 'a_value'. Identifiers (column names and tables names) can be used unquoted if they don't contain special characters or are not a SQL reserved keyword. Otherwise they must be surrounded with double-quote characters. e.g. WHERE "from" = 5.

This means the now only two valid options to pass are

- WHERE a_field = 'a_value'

- WHERE "a_field" = 'a_value'

whilst the whole where clause or sql statement must be quoted as well (both in .yaml config or if used on the command line e.g. mapproxy-util export --coverage ...)

## Expected Behavior

to work again like when using ogrinfo or ogr2ogr on the CLI with -where or -sql option

## Actual Behavior

Mapproxy fails with:

> Traceback (most recent call last):
>   File "/home/mapproxy/venv/bin/mapproxy-util", line 11, in <module>
>     sys.exit(main())
>   File "/home/mapproxy/venv/lib/python3.5/site-packages/mapproxy/script/util.py", line 387, in main
>     commands[command]['func'](args)
>   File "/home/mapproxy/venv/lib/python3.5/site-packages/mapproxy/script/export.py", line 274, in export_command
>     base_path=os.getcwd())
>   File "/home/mapproxy/venv/lib/python3.5/site-packages/mapproxy/config/coverage.py", line 96, in load_coverage
>     geom = load_datasource(datasource, where)
>   File "/home/mapproxy/venv/lib/python3.5/site-packages/mapproxy/util/geom.py", line 74, in load_datasource
>     return load_ogr_datasource(datasource, where=where)
>   File "/home/mapproxy/venv/lib/python3.5/site-packages/mapproxy/util/geom.py", line 103, in load_ogr_datasource
>     raise CoverageReadError(ex)
> mapproxy.util.geom.CoverageReadError: b'"name" not recognised as an available field.'

or

> mapproxy.util.geom.CoverageReadError: b'Type mismatch or improper type of arguments to = operator.'

## Possible Fix

adopt the parameter passing into OGR in mapproxy.util.ogr

[https://github.com/mapproxy/mapproxy/blob/668b6202d89ac8315c79b2606a458ee3a77c35c2/mapproxy/util/ogr.py#L106](https://github.com/mapproxy/mapproxy/blob/668b6202d89ac8315c79b2606a458ee3a77c35c2/mapproxy/util/ogr.py#L106)
until here, a correct quoted "where parameter" is still correct quoted when passed into OGR_DS_ExecuteSQL()

>>> print(where)
"select * from OGRGeoJSON where CNTRY_NAME = 'Germany'"

>>> print(where.encode('utf-8'))
b"select * from OGRGeoJSON where CNTRY_NAME = 'Germany'"

## Steps to Reproduce

I did not try with OSGEO OGR, only with LIBOGR (GDAL/OGR package)
if where parameter is used with numeric field (e.g. 'where id = 137') it works as expected

.yaml config with coverage and where clause
it doesn't matter how the quoting is set or if it's a complete sql statement

or

on the CLI e.g. (it doesn't matter how the quoting is set or if it's a complete sql statement)

> mapproxy-util export -f test.yaml --source test_basemap_cache --levels 1..5 --grid mygrid --dest cache_data/test_cache --type mapproxy --coverage coverage/test_bugreport.geojson --where 'CNTRY_NAME = Germany' --srs 3857 
> mapproxy-util export -f test.yaml --source test_basemap_cache --levels 1..12 --grid mygrid --dest cache_data/test_cache --type mapproxy --coverage coverage/test_bugreport.geojson --where 'CNTRY_NAME = "Germany"' --srs 3857 
> mapproxy-util export -f test.yaml --source test_basemap_cache --levels 1..12 --grid mygrid --dest cache_data/test_cache --type mapproxy --coverage coverage/test_bugreport.geojson --where "CNTRY_NAME = Germany" --srs 3857 
> mapproxy-util export -f test.yaml --source test_basemap_cache --levels 1..12 --grid mygrid --dest cache_data/test_cache --type mapproxy --coverage coverage/test_bugreport.geojson --where "\"CNTRY_NAME\" = 'Germany'" --srs 3857 
> mapproxy-util export -f test.yaml --source test_basemap_cache --levels 1..12 --grid mygrid --dest cache_data/test_cache --type mapproxy --coverage coverage/test_bugreport.geojson --where "CNTRY_NAME = 'Germany'" --srs 3857 
> mapproxy-util export -f test.yaml --source test_basemap_cache --levels 1..12 --grid mygrid --dest cache_data/test_cache --type mapproxy --coverage coverage/test_bugreport.geojson --where 'CNTRY_NAME = \'Germany\'' --srs 3857 
> mapproxy-util export -f test.yaml --source test_basemap_cache --levels 1..12 --grid mygrid --dest cache_data/test_cache --type mapproxy --coverage coverage/test_bugreport.geojson --where 'CNTRY_NAME = 'Germany'' --srs 3857 

## Your Environment

* Version used: Mapproxy 1.11.0
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 3.5.3
* Operating System and version: Debian 9.4
*GDAL/OGR: 2.1.2 (Debian Package)

**Comment by olt** [comment]
I was able to reproduce this, but I was also able to fix this by quoting strings with single-quotes.
I've updated the tests and examples in the documentation.
