### ISSUE TITLE
Mapproxy GetCapabilities internal error

### ISSUE THREAD

**Issue by simonseyock** [mapproxy/mapproxy#383]
## Context
I try to run mapproxy on a windows server.

## Expected Behavior
mapproxy should serve a getcapabilities document under the url `/service?request=GetCapabilities`

## Actual Behavior
mapproxy shows `internal server error` and the following stack trace occurs:
```
CRITICAL:mapproxy.wsgiapp:fatal error in service for /service?request=GetCapabilities
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\mapproxy\wsgiapp.py", line 193, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\ows.py", line 38, in handle
    return self.services[service].handle(req)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\base.py", line 30, in handle
    return handler(parsed_req)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\wms.py", line 198, in capabilities
    ).render(map_request)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\wms.py", line 518, in render
    return self._render_template(_map_request.capabilities_template)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\wms.py", line 540, in _render_template
    max_output_size=max_output_size,
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 167, in substitute
    result, defs, inherit = self._interpret(ns)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 178, in _interpret
    self._interpret_codes(self._parsed, ns, out=parts, defs=defs)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 206, in _interpret_codes
    self._interpret_code(item, ns, out, defs)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 226, in _interpret_code
    base = self._eval(parts[0], ns, pos)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 301, in _eval
    reraise((exc_info[0], e, exc_info[2]))
  File "c:\program files\python36\lib\site-packages\mapproxy\util\py.py", line 40, in reraise
    raise exc.with_traceback(tb)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 288, in _eval
    value = eval(code, self.default_namespace, ns)
  File "<string>", line 1, in <module>
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 519, in __call__
    values = self._parse_signature(args, kw)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 562, in _parse_signature
    % ', '.join(repr(v) for v in args))
TypeError: Extra position arguments: True at line 312 column 3 in file c:\program files\python36\lib\site-packages\mapproxy\service\templates\wms130capabilities.xml
```

Note that the same error occurs if using `mapproxy-utils serve-develop`

## Steps to Reproduce
The error occurs with this mapproxy.yaml:
```
parts:
  coverages:
    nrw_histortho_coverage: &nrw_histortho_coverage
      bbox: [7.086899524483748, 50.73835634200705, 7.093765979561875, 50.74137095170616]
      srs: 'EPSG:4326'

services:
  demo:
  wms:
    srs: ['EPSG:4326', 'EPSG:3857']
    image_formats: ['image/png', 'image/jpeg']

layers:
  - name: nrw_histortho
    title: Historic orthographic WMS NRW
    sources: [nrw_histortho_source]

sources:
  nrw_histortho_source:
    type: wms
    coverage: *nrw_histortho_coverage
    req:
      url: http://www.wms.nrw.de/geobasis/wms_nw_histortho_1988-1994?
      layers: nw_histortho_1988-1994
    wms_opts:
      version: '1.3.0'
    image:
      format: 'image/png'
    supported_srs: ['EPSG:4326']

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
```

## Context
This bug prevents me from loading the mapproxy wms into the desired client (mapbender) because it needs to read the capabilities.

## Your Environment
python: 3.6
mapproxy: master

**Comment by simonseyock** [comment]
Sorry for double post, Somehow the issue was not showing up in my list.
