### ISSUE TITLE
GetCapabilities request results in internal error

### ISSUE THREAD

**Issue by simonseyock** [mapproxy/mapproxy#384]
## Context
I am trying to get mapproxy to run on windows. The WMS is accesible and working via `request=GetMap`

## Expected Behavior
mapproxy should serve a getcapabilities document at `/service?request=GetCapabilities`

## Actual Behavior
the page shows `internal error` and the stack trace looks like this:

```
CRITICAL:mapproxy.wsgiapp:fatal error in service for /service?request=GetCapabilities
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\mapproxy\wsgiapp.py", line 193, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\ows.py", line 38, in handle
    return self.services[service].handle(req)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\base.py", line 30, in handle
    return handler(parsed_req)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\wms.py", line 198, in capabilities
    ).render(map_request)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\wms.py", line 518, in render
    return self._render_template(_map_request.capabilities_template)
  File "c:\program files\python36\lib\site-packages\mapproxy\service\wms.py", line 540, in _render_template
    max_output_size=max_output_size,
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 167, in substitute
    result, defs, inherit = self._interpret(ns)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 178, in _interpret
    self._interpret_codes(self._parsed, ns, out=parts, defs=defs)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 206, in _interpret_codes
    self._interpret_code(item, ns, out, defs)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 226, in _interpret_code
    base = self._eval(parts[0], ns, pos)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 301, in _eval
    reraise((exc_info[0], e, exc_info[2]))
  File "c:\program files\python36\lib\site-packages\mapproxy\util\py.py", line 40, in reraise
    raise exc.with_traceback(tb)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 288, in _eval
    value = eval(code, self.default_namespace, ns)
  File "<string>", line 1, in <module>
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 519, in __call__
    values = self._parse_signature(args, kw)
  File "c:\program files\python36\lib\site-packages\mapproxy\util\ext\tempita\__init__.py", line 562, in _parse_signature
    % ', '.join(repr(v) for v in args))
TypeError: Extra position arguments: True at line 312 column 3 in file c:\program files\python36\lib\site-packages\mapproxy\service\templates\wms130capabilities.xml
```

This error happens if i serve mapproxy via waitress or with `mapproxy-util serve-develop`

## Steps to Reproduce
I use the following mapproxy.yaml:
```
parts:
  coverages:
    nrw_histortho_coverage: &nrw_histortho_coverage
      bbox: [7.086899524483748, 50.73835634200705, 7.093765979561875, 50.74137095170616]
      srs: 'EPSG:4326'

services:
  demo:
  wms:
    srs: ['EPSG:4326', 'EPSG:3857']
    image_formats: ['image/png', 'image/jpeg']

layers:
  - name: nrw_histortho
    title: Historic orthographic WMS NRW
    sources: [nrw_histortho_source]

sources:
  nrw_histortho_source:
    type: wms
    coverage: *nrw_histortho_coverage
    req:
      url: http://www.wms.nrw.de/geobasis/wms_nw_histortho_1988-1994?
      layers: nw_histortho_1988-1994
    wms_opts:
      version: '1.3.0'
    image:
      format: 'image/png'
    supported_srs: ['EPSG:4326']

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
```

## Context
I can't load the mapproxy in my client (mapbender) without the capabilites document.

## Your Environment
Python: 3.6
mapproxy: current master

**Comment by simonseyock** [comment]
Please also note that the same error happens if append `&VERSION=1.3.0` or any other version.

**Comment by simonseyock** [comment]
Please also take note that an equivalent error occurs if I append `&VERSION=1.3.0` or any other version.

**Comment by simonseyock** [comment]
Ok, I redid everything on another machine and it works. It has to be some configuration / installation problem. I will try to find out what was causing this.

This worked:
```
git clone mapproxy
virtualenv.py /Python36     # Python 3.6.3
pip install Pillow          # Pillow 5.3.0
pip install PyYAML          # PyYAML 3.13
pip install pyproj.whl      # from Unofficial Windows Binaries for Python Extension Packages by Christoph Gohlke
                            # 32 bit v 1.9.5.1
python setup.py build
python setup.py install
source mapproxy-venv/Scripts/activate
mapproxy-util --version     # Proxy 1.12.0a0.post20181107
mapproxy-util create -t base-config mymapproxy
mapproxy-util serve-develop mapproxy.yaml
```

I will close this for now.

**Comment by olt** [comment]
Any chance you had 3.6.7 on your first system?

There was a change in the Python tokenize library that might have caused this issue on Windows. 
There is a workaround for this issue in 81c84d47bbc77da324c36ca718fbca7dde1c1c66

**Comment by daniviga** [comment]
I can confirm the issue with Python 3.6.7 and 1.11.0:

```bash
bash-4.4$ python3 --version
Python 3.6.7
```
master is working properly.
