### ISSUE TITLE
proj_data_dir config option not working

### ISSUE THREAD

**Issue by gavinharriss** [mapproxy/mapproxy#493]
## Context
Providing custom projections via the proj_data_dir option is not working.

## Expected Behavior
Custom EPSG projections should become available for use through the MapProxy yaml config file as described in  https://mapproxy.org/docs/latest/configuration.html

## Actual Behavior
When attempting to use non-standard EPSG's in mapproxy.yaml, provided through the proj_data_dir setting, an error is thrown.

## Steps to Reproduce

1. Define a custom projections text file named "epsg" with the following contents:
```
<100000> +proj=lcc +lat_1=-25 +lat_2=-32 +lat_0=-28.5 +lon_0=24.5 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs <>

# Standard EPSG's we're also using in the *.yaml config file
# Copied from http://epsg.io/
<3857> +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs <>
<27200> +proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +towgs84=59.47,-5.04,187.44,0.47,-0.1,1.024,-4.5993 +units=m +no_defs <>
```
2. Reference the "epsg" file location (in a directory also called "epsg" in this case) in the mapproxy.yaml configuration file:
```
services:
  demo:
  tms:
    use_grid_names: true
  kml:
      use_grid_names: true
  wmts:
  wms:
    srs: ['EPSG:3857','EPSG:100000']
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: satellite
    title: Mapbox Satellite
    sources: [satellite_cache]
  - name: satellite_custom
    title: Mapbox Satellite reprojected as custom map grid
    sources: [satellite_custom_cache]
    
caches:
  satellite_cache:
    grids: [mapbox_grid]
    sources: [satellite_tiles]
  satellite_custom_cache:
    grids: [custom_grid]
    sources: [satellite_cache]
    
sources:
  satellite_tiles:
    type: tile
    url: https://api.mapbox.com/v4/mapbox.satellite/%(z)s/%(x)s/%(y)s.png?access_token=[REDACTED]
    grid: mapbox_grid
    
grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
  mapbox_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: 'nw'
  custom_grid:
    srs: 'EPSG:100000'
    origin: 'nw'
    
globals:
  srs:
    proj_data_dir: 'epsg\'
```
3. Run MapProxy `mapproxy-util serve-develop mapproxy.yaml`.
4. Get the following error:
```
C:\Python>mapproxy-util serve-develop mapproxy.yaml
[2021-02-12 11:44:45,052] mapproxy.config - INFO - reading: C:\Python\mappoxy.yaml
[2021-02-12 11:44:45,058] mapproxy.system - INFO - loading proj data from C:\Python\epsg\
Traceback (most recent call last):
  File "c:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python39\Scripts\mapproxy-util.exe\__main__.py", line 7, in <module>
  File "c:\python\python39\lib\site-packages\mapproxy\script\util.py", line 387, in main
    commands[command]['func'](args)
  File "c:\python\python39\lib\site-packages\mapproxy\script\util.py", line 85, in serve_develop_command
    app = make_wsgi_app(mapproxy_conf, debug=options.debug)
  File "c:\python\python39\lib\site-packages\mapproxy\wsgiapp.py", line 58, in make_wsgi_app
    services = conf.configured_services()
  File "c:\python\python39\lib\site-packages\mapproxy\config\loader.py", line 211, in configured_services
    return self.services.services()
  File "c:\python\python39\lib\site-packages\mapproxy\config\loader.py", line 1855, in services
    new_services = creator(service_conf or {})
  File "c:\python\python39\lib\site-packages\mapproxy\config\loader.py", line 2018, in demo_service
    lyr = layer_conf.wms_layer()
  File "c:\python\python39\lib\site-packages\mapproxy\util\py.py", line 78, in wrapper
    cache[key] = func(self, *args, **kwargs)
  File "c:\python\python39\lib\site-packages\mapproxy\config\loader.py", line 1683, in wms_layer
    map_layer = self.context.caches[source_name].map_layer()
  File "c:\python\python39\lib\site-packages\mapproxy\util\py.py", line 78, in wrapper
    cache[key] = func(self, *args, **kwargs)
  File "c:\python\python39\lib\site-packages\mapproxy\config\loader.py", line 1599, in map_layer
    for grid, extent, tile_manager in self.caches():
  File "c:\python\python39\lib\site-packages\mapproxy\util\py.py", line 78, in wrapper
    cache[key] = func(self, *args, **kwargs)
  File "c:\python\python39\lib\site-packages\mapproxy\config\loader.py", line 1503, in caches
    sources, source_image_opts = self._sources_for_grid(
  File "c:\python\python39\lib\site-packages\mapproxy\config\loader.py", line 1376, in _sources_for_grid
    tile_grid=grid_conf.tile_grid(),
  File "c:\python\python39\lib\site-packages\mapproxy\util\py.py", line 78, in wrapper
    cache[key] = func(self, *args, **kwargs)
  File "c:\python\python39\lib\site-packages\mapproxy\config\loader.py", line 300, in tile_grid
    grid = tile_grid(
  File "c:\python\python39\lib\site-packages\mapproxy\grid.py", line 101, in tile_grid
    srs = SRS(srs)
  File "c:\python\python39\lib\site-packages\mapproxy\srs.py", line 96, in SRS
    srs = _srs_impl(srs_code)
  File "c:\python\python39\lib\site-packages\mapproxy\srs.py", line 320, in __init__
    self.proj = CRS.from_epsg(epsg_num)
  File "c:\python\python39\lib\site-packages\pyproj\crs\crs.py", line 331, in from_epsg
    return CRS(_prepare_from_epsg(code))
  File "c:\python\python39\lib\site-packages\pyproj\crs\crs.py", line 296, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2302, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: epsg:100000: (Internal Proj Error: proj_create: crs not found)
```

## Context
Unable to utilise custom projections in MapProxy.

## Your Environment
* Version used: 1.13.0
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 3.9
* Operating System and version: Windows 10 (64 bit)

**Comment by gavinharriss** [comment]
Further investigations seems to suggest that the proj_data_dir does work but only if it contains the proj.db file. All other files alongside proj.db seem to be ignored. 

Experimenting without using the proj_data_dir and trying to use projections from non proj.db files hosted in C:\Python\Python39\Lib\site-packages\pyproj\proj_dir\share\proj e.g. EPSG:42311 from the other.extra file does not work either.

The same error is encountered:
`pyproj.exceptions.CRSError: Invalid projection: epsg:4326: (Internal Proj Error: proj_create: no database context specified)`

It looks like I need to work out how to add my custom projection to the SQLite DB tables within proj.db.

**Comment by gavinharriss** [comment]
Digging deeper I think that EPSG definitions will only be pulled from the proj.db database by pyproj, so the 'epsg' file that the MapProxy docs mention doesn't get picked up.

As I workaround I tried to use a custom authority of 'xxxx' by using an 'xxxx' file and using the srs of 'XXXX:100000' in mapproxy.yaml. Unfortunately, MapProxy takes 'XXXX:100000' and converts it to 'EPSG:100000' so the 'xxxx' doesn't get used. I see the error `pyproj.exceptions.CRSError: Invalid projection: epsg:100000: (Internal Proj Error: proj_create: crs not found)`.

I also tried the experiment using an existing projection from other.extra by using the srs 'other.extra:42311', but again the authority seems to be replaced as the same error resulted: `pyproj.exceptions.CRSError: Invalid projection: epsg:42311: (Internal Proj Error: proj_create: crs not found)`.

If MapProxy respected the configured authority maybe these custom projection files would be picked up correctly?

**Comment by gavinharriss** [comment]
Potential solution: Hopefully if MapProxy stopped overriding the srs authority with 'EPSG' then current non-EPSG projections such as ESRI:* would start to work, and custom projection files could be dropped in using other authority identifiers other than epsg, to bring back support for custom projections without the need to hack a copy of the proj.db file.

**Comment by olt** [comment]
I admit that the documentation is sparse on that topic (but it is not a common use case anyhow).
The gist is that PROJ>=5 uses a different configuration format. The old text file format is no longer supported.

**Comment by gavinharriss** [comment]
All good, it's a great project and I figured I was probably doing edge case stuff. I can see from my investigations that the PROJ library had evolved but MapProxy had fallen behind its conventions. Without a good understanding of the code base, it does look like it might be an easy fix though, if authorities other than EPSG are allowed (by stop forcing EPSG to be used).
