### ISSUE TITLE
list index out of range during mapproxy_seed

### ISSUE THREAD

**Issue by FrankyBoy** [mapproxy/mapproxy#511]
I'm running into a peculiar "index out of range" exception when trying to seed a new project. This bbox as returned by arcgis server is not considered valid: ` [1794923, 6162242, 1810124, 6179625]`. However a similar bbox `[1784939, 6162115, 1820807, 6180861]` is accepted as valid for (to me at least) no apparent reason. The only difference seems to be that the 2nd bbox is larger (i.e. 1st is ~ 15x19km, 2nd is ~35x19km).

Output of ` mapproxy-seed -f myproj.yaml -c 8 ./seeds/myproj_seed.yaml` (seeding lvls 15-19):
```
========== Seeding tasks ==========
Start seeding process (1 task)
  seed_all:
    Seeding cache 'stockerau_flaewi2020_cache' with grid 'stockerau_flaewi2020_web_mercator' in EPSG:3857
    Limited to coverage in: 16.12407, 48.33185, 16.26062, 48.43556 (EPSG:4326)
    Levels: [15, 16, 17, 18, 19]
    Overwriting: no tiles
Traceback (most recent call last):
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/grid.py", line 968, in get_affected_level_tiles
    return self._tile_iter(x0, y0, x1, y1, level)
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/grid.py", line 982, in _tile_iter
    ll = (xs[0], ys[-1], level)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdc1/mapproxy/venv_392/bin/mapproxy-seed", line 8, in <module>
    sys.exit(main())
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/seed/script.py", line 361, in main
    return SeedScript()()
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/seed/script.py", line 244, in __call__
    seed(seed_tasks, progress_logger=logger, dry_run=options.dry_run,
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/seed/seeder.py", line 498, in seed
    seed_task(task, concurrency, dry_run, skip_geoms_for_last_levels, progress_logger,
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/seed/seeder.py", line 527, in seed_task
    tile_walker.walk()
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/seed/seeder.py", line 326, in walk
    self._walk(bbox, self.task.levels)
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/seed/seeder.py", line 338, in _walk
    bbox_, tiles, subtiles = self.grid.get_affected_level_tiles(cur_bbox, current_level)
  File "/mnt/sdc1/mapproxy/venv_392/lib/python3.9/site-packages/mapproxy/grid.py", line 970, in get_affected_level_tiles
    raise GridError('Invalid BBOX')
mapproxy.grid.GridError: Invalid BBOX
```

The project file looks like this:

```
caches:
  myproj_cache:
    meta_size: [8, 8]
    meta_buffer: 0
    grids:
    - myproj_web_mercator
    sources:
    - myproj_src
    cache:
      type: geopackage
      filename: ./cache_data/myproj.gpkg

grids:
  myproj_web_mercator:
    bbox: [1794923, 6162242, 1810124, 6179625]
    bbox_srs: EPSG:3857
    origin: nw
    res:
    [removed for brevity - just the usual 19 cache levels]
    srs: EPSG:3857

layers:
- name: myproj_basemap
  sources:
  - myproj_cache
  title: myproj_basemap

services:
  demo:
  wmts:
    kvp: false
    restful: true

sources:
  myproj_src:
    image:
      transparent_color: '#64FF32'
      transparent_color_tolerance: 0
    coverage:
       bbox: [1794923, 6162242, 1810124, 6179625]
       bbox_srs: EPSG:3857

    req:
      layers: 0,1,2,3
      transparent: true
      url: [redacted]
    supported_formats:
    - png
    supported_srs:
    - EPSG:3857
    type: wms
    wms_opts:
      featureinfo: true
      version: 1.3.0
    http:
      client_timeout: 600 # seconds

globals:
  image:
    [removed for brevity]
```

**Comment by FrankyBoy** [comment]
So I was poking around a bit and found the root cause: The calculation of the delta here: https://github.com/mapproxy/mapproxy/blob/master/mapproxy/grid.py#L956

As my extent is relatively small, this code results in (in my case) x1 becoming -1 at low zoom levels. 

Th me this delta calculation seems very questionable to begin with, as it might remove up to 1/10th of a tile on each side if I interpret this code correctly (and I think I actually have this exact problem of one corner being cut off with another project). 

So my suggestion is to simply get rid of the delta variable.

**Comment by tobwen** [comment]
Adaptive workaround. Warning: untested.

``` python
delta = self.grid.resolutions[level] / (2.0 * (self.grid.resolutions[level] // min((bbox[2] - bbox[0]), (bbox[3] - bbox[1]))))
```

**Comment by FrankyBoy** [comment]
Thb I don't see the point of this delta calculation to begin with. Even if a tile would only contain a tiny fraction of my map, I don't want my map to be arbitrarily cut off because "wasteful" (or whatever). My suggestion remains to remove this pointless complexity.

**Comment by tobwen** [comment]
@olt Could you please drop a line, why you added this delta?
