### ISSUE TITLE
Issue with proj.db in docker version 

### ISSUE THREAD

**Issue by jaykayone** [mapproxy/mapproxy#666]
There seems to be an issue with proj.db in the docker release

## Context

When starting the container with one of my configs that works in a kartoza container, I get the following error

2023-04-25 15:26:51 Found libproj >=5. Using this library without pyproj is deprecated and not fully supported. Please install pyproj >= 2.
2023-04-25 15:26:51 [2023-04-25 13:26:51,409] mapproxy.config - INFO - reading: /mapproxy/config/mapproxy.yaml
2023-04-25 15:26:52 [2023-04-25 13:26:52,101] mapproxy.system - INFO - loading proj data from /usr/local/share/proj/
2023-04-25 15:26:52 proj_create: Cannot find proj.db
2023-04-25 15:26:52 proj_create: no database context specified
2023-04-25 15:26:52 Traceback (most recent call last):
2023-04-25 15:26:52   File "/usr/local/bin/mapproxy-util", line 8, in <module>
2023-04-25 15:26:52     sys.exit(main())
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/script/util.py", line 403, in main
2023-04-25 15:26:52     commands[command]['func'](args)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/script/util.py", line 86, in serve_develop_command
2023-04-25 15:26:52     app = make_wsgi_app(mapproxy_conf, debug=options.debug)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/wsgiapp.py", line 58, in make_wsgi_app
2023-04-25 15:26:52     services = conf.configured_services()
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 212, in configured_services
2023-04-25 15:26:52     return self.services.services()
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 1968, in services
2023-04-25 15:26:52     new_services = creator(service_conf or {})
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 2132, in demo_service
2023-04-25 15:26:52     lyr = layer_conf.wms_layer()
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/util/py.py", line 78, in wrapper
2023-04-25 15:26:52     cache[key] = func(self, *args, **kwargs)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 1750, in wms_layer
2023-04-25 15:26:52     map_layer = self.context.caches[source_name].map_layer()
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/util/py.py", line 78, in wrapper
2023-04-25 15:26:52     cache[key] = func(self, *args, **kwargs)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 1666, in map_layer
2023-04-25 15:26:52     for grid, extent, tile_manager in self.caches():
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/util/py.py", line 78, in wrapper
2023-04-25 15:26:52     cache[key] = func(self, *args, **kwargs)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 1567, in caches
2023-04-25 15:26:52     sources, source_image_opts = self._sources_for_grid(
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 1448, in _sources_for_grid
2023-04-25 15:26:52     source = source_conf.source({'format': request_format})
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 783, in source
2023-04-25 15:26:52     coverage = self.coverage()
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/util/py.py", line 78, in wrapper
2023-04-25 15:26:52     cache[key] = func(self, *args, **kwargs)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/loader.py", line 569, in coverage
2023-04-25 15:26:52     return load_coverage(self.conf['coverage'])
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/config/coverage.py", line 107, in load_coverage
2023-04-25 15:26:52     return coverage(geom or bbox, SRS(srs), clip=clip)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/srs.py", line 109, in SRS
2023-04-25 15:26:52     srs = _srs_impl(srs_code)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/srs.py", line 146, in __init__
2023-04-25 15:26:52     self.proj = Proj(init='epsg:%d' % epsg_num)
2023-04-25 15:26:52   File "/usr/local/lib/python3.10/site-packages/mapproxy/proj.py", line 173, in __init__
2023-04-25 15:26:52     raise ProjInitError('error initializing Proj(proj_def=%r, init=%r): %s' %
2023-04-25 15:26:52 mapproxy.proj.ProjInitError: error initializing Proj(proj_def=None, init='epsg:2169'): b'no arguments in initialization list'

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: ghcr.io/mapproxy/mapproxy/mapproxy:1.16.0-nginx
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9):
* Server type and version:
* Operating System and version:

**Comment by weskamm** [comment]
Could you provide your mapproxy.yaml to see what the problem causes?

**Comment by weskamm** [comment]
closing due to inactivity
