### ISSUE TITLE
[fatal error] Mapnik multithreaded: 'Map' object has no attribute 'map_object_pid'

### ISSUE THREAD

**Issue by tobwen** [mapproxy/mapproxy#674]
## Context
If the same mapnik layer is overlaid twice, a fatal error occurs.

## Expected Behavior
no fatal error

## Actual Behavior
<details>
 <summary>Log of fatal error 'Map' object has no attribute 'map_object_pid'</summary>

``` Python3
[2023-05-14 08:35:33,457] mapproxy.source.request - INFO - API /opt/mapproxy/mymapproxy/test.xml:(781950.7993573541,6642530.6320383875,793263.4795435581,6653843.312224594):EPSG:3857:(1184,1184) 200 230.9 232
[2023-05-14 08:35:33,530] mapproxy.wsgiapp - CRITICAL - fatal error in service for /service?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=mapnik&CRS=EPSG%3A3857&STYLES=&WIDTH=1175&HEIGHT=900&BBOX=780675.931080735%2C6637719.061300509%2C799781.6565014198%2C6652353.233963162
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/wsgiapp.py", line 141, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/ows.py", line 38, in handle
    return self.services[service].handle(req)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/base.py", line 30, in handle
    return handler(parsed_req)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/wms.py", line 135, in map
    renderer.render(merger)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/wms.py", line 592, in render
    return self._render_capture_source_errors(async_pool, render_layers,
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/wms.py", line 630, in _render_capture_source_errors
    reraise(ex)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/py.py", line 40, in reraise
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 132, in _single_call
    result = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/wms.py", line 642, in _render_layer
    layer_img = layer.get_map(self.query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/layer.py", line 414, in get_map
    result = self._image(query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/layer.py", line 447, in _image
    tile_collection = self.tile_manager.load_tile_coords(affected_tile_coords, with_metadata=query.tiled_only, dimensions=query.dimensions)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 144, in load_tile_coords
    tiles = self._load_tile_coords(
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 176, in _load_tile_coords
    created_tiles = creator.create_tiles(uncached_tiles)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 355, in create_tiles
    created_tiles = self._create_meta_tiles(meta_tiles)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 451, in _create_meta_tiles
    return self._create_threaded(self._create_meta_tile, meta_tiles)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 371, in _create_threaded
    for new_tiles in async_pool.imap(create_func, tiles):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 45, in _result_iter
    for result in results:
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 119, in map_each
    for value in self._get_results(next_result, results, raise_exceptions):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 163, in _get_results
    for i, value in self._fetch_results(raise_exceptions):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 184, in _fetch_results
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 72, in run
    result = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 469, in _create_meta_tile
    meta_tile_image = self._query_sources(query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 436, in _query_sources
    for layer in async_.imap(get_map_from_source, self.sources):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 45, in _result_iter
    for result in results:
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 119, in map_each
    for value in self._get_results(next_result, results, raise_exceptions):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 163, in _get_results
    for i, value in self._fetch_results(raise_exceptions):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 184, in _fetch_results
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 72, in run
    result = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 429, in get_map_from_source
    img = source.get_map(query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 119, in get_map
    resp = self.render(query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 137, in render
    return self.render_mapfile(mapfile, query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 224, in render_mapfile
    return run_non_blocking(self._render_mapfile, (mapfile, query))
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 224, in run_non_blocking
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 229, in _render_mapfile
    m = self.map_obj(mapfile)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 216, in map_obj
    self._map_cache()[cachekey] = self._get_map_obj(mapfile)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 156, in _get_map_obj
    if m.map_object_pid == process_id:
AttributeError: 'Map' object has no attribute 'map_object_pid'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/wsgiapp.py", line 141, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/ows.py", line 38, in handle
    return self.services[service].handle(req)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/base.py", line 30, in handle
    return handler(parsed_req)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/wms.py", line 135, in map
    renderer.render(merger)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/wms.py", line 592, in render
    return self._render_capture_source_errors(async_pool, render_layers,
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/wms.py", line 630, in _render_capture_source_errors
    reraise(ex)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/py.py", line 40, in reraise
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 132, in _single_call
    result = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/service/wms.py", line 642, in _render_layer
    layer_img = layer.get_map(self.query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/layer.py", line 414, in get_map
    result = self._image(query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/layer.py", line 447, in _image
    tile_collection = self.tile_manager.load_tile_coords(affected_tile_coords, with_metadata=query.tiled_only, dimensions=query.dimensions)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 144, in load_tile_coords
    tiles = self._load_tile_coords(
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 176, in _load_tile_coords
    created_tiles = creator.create_tiles(uncached_tiles)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 355, in create_tiles
    created_tiles = self._create_meta_tiles(meta_tiles)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 451, in _create_meta_tiles
    return self._create_threaded(self._create_meta_tile, meta_tiles)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 371, in _create_threaded
    for new_tiles in async_pool.imap(create_func, tiles):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 45, in _result_iter
    for result in results:
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 119, in map_each
    for value in self._get_results(next_result, results, raise_exceptions):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 163, in _get_results
    for i, value in self._fetch_results(raise_exceptions):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 184, in _fetch_results
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 72, in run
    result = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 469, in _create_meta_tile
    meta_tile_image = self._query_sources(query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 436, in _query_sources
    for layer in async_.imap(get_map_from_source, self.sources):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 45, in _result_iter
    for result in results:
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 119, in map_each
    for value in self._get_results(next_result, results, raise_exceptions):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 163, in _get_results
    for i, value in self._fetch_results(raise_exceptions):
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 184, in _fetch_results
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 72, in run
    result = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/cache/tile.py", line 429, in get_map_from_source
    img = source.get_map(query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 119, in get_map
    resp = self.render(query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 137, in render
    return self.render_mapfile(mapfile, query)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 224, in render_mapfile
    return run_non_blocking(self._render_mapfile, (mapfile, query))
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/util/async_.py", line 224, in run_non_blocking
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 229, in _render_mapfile
    m = self.map_obj(mapfile)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 216, in map_obj
    self._map_cache()[cachekey] = self._get_map_obj(mapfile)
  File "/usr/local/lib/python3.9/dist-packages/mapproxy/source/mapnik.py", line 156, in _get_map_obj
    if m.map_object_pid == process_id:
AttributeError: 'Map' object has no attribute 'map_object_pid'
```
</details>

## Possible Fix
Disable _multithreaded_ :(
```
multithreaded: false
```

## Steps to Reproduce
<details>
 <summary>mapproxy config</summary>

``` YAML
services:
  demo:
  tms:
    use_grid_names: true
    origin: 'nw'

layers:
  - name: mapnik1
    title: Mapnik1
    sources: [mapnik_cache]
  - name: mapnik2
    title: Mapnik2
    sources: [mapnik_cache, mapnik_source]
  - name: mapnik3
    title: Mapnik3
    sources: [mapnik_source, mapnik_source]

caches:
  mapnik_cache:
    grids: [webmercator]
    sources: [mapnik_source, mapnik_source]

sources:
  mapnik_source:
    type: mapnik
    mapfile: test.xml
    layers: kacheln
    transparent: true
    multithreaded: true

grids:
    webmercator:
        base: GLOBAL_WEBMERCATOR

globals:
```
</details>

<details>
 <summary>Mapnik config</summary>

``` XML
<?xml version="1.0" encoding="utf-8"?>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs" background-color="rgba(0,0,0,0.0)">
  <Style name="kacheln">
    <Rule>
      <Filter>([value]=1)</Filter>
      <PolygonSymbolizer fill="rgb(58,92,157)"/>
    </Rule>
    <Rule>
      <Filter>([value]=2)</Filter>
      <PolygonSymbolizer fill="rgb(109,188,227)"/>
    </Rule>
    <Rule>
      <Filter>([value]=3)</Filter>
      <PolygonSymbolizer fill="rgb(151,153,153)"/>
    </Rule>
    <Rule>
      <Filter>([value]=4)</Filter>
      <PolygonSymbolizer fill="rgb(135,188,0)"/>
    </Rule>
    <Rule>
      <Filter>([value]=5)</Filter>
      <PolygonSymbolizer fill="rgb(52,72,0)"/>
    </Rule>
    <Rule>
      <LineSymbolizer stroke-width="0"/>
    </Rule>
  </Style>
  <Layer name="kacheln" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs">
    <StyleName>kacheln</StyleName>
    <Datasource>
      <Parameter name="base">/opt/shapefiles/</Parameter>
      <Parameter name="file">test</Parameter>
      <Parameter name="type">shape</Parameter>
    </Datasource>
  </Layer>
</Map>
```
</details>

## Context
Mapnik's AGG renderer creates semi-transparent subpixels between two adjacent polygons. To fill these subpixels with content, a common approach is to duplicate the layer. The backend doesn't matter. I tried Shapefile and PostgreSQL.

## Your Environment
* Version used: MapProxy 1.16.0.post20230514, py3-mapnik: 1:0.0~20200224-7da019cf9-3, libmapnik: 3.1.0+ds-1
* Environment name and version: Python 3.9.2
* Server type and version: AMD64
* Operating System and version: Debian Bullseye

**Comment by tobwen** [comment]
@ArneBab PTAL

**Comment by ArneBab** [comment]
> @ArneBab PTAL

I’ll search for a fix — thank you for the ping!

**Comment by tobwen** [comment]
Just found it!

https://github.com/mapproxy/mapproxy/blob/fa1010450060da1d43ba34bb5a80024481a225d7/mapproxy/source/mapnik.py#L156

That's wrong. It should be `m` has `map_obj_pid` only, not `map_object_pid`.

**Comment by ArneBab** [comment]
> > > @ArneBab PTAL
> > 
> > 
> > I’ll search for a fix — thank you for the ping!
> 
> Just found it!
> 
> https://github.com/mapproxy/mapproxy/blob/fa1010450060da1d43ba34bb5a80024481a225d7/mapproxy/source/mapnik.py#L156
> 
> That's wrong. `m` has `map_obj_pid` only, not `map_object_pid`.
> 
> See:
> 
> https://github.com/mapproxy/mapproxy/blob/fa1010450060da1d43ba34bb5a80024481a225d7/mapproxy/source/mapnik.py#L142

Arg, refactoring … thank you!

**Comment by tobwen** [comment]
> Arg, refactoring … thank you! Will you commit it or shall I file a PR?

Please do it because I don't want the big responsibility of choosing one of the two variable names, hehe.

However, I am considering bringing ThreadPoolExecutor in to have more control over the number of threads. If I am successful, I will offer a PR for it.

**Comment by tobwen** [comment]
I've just PRed a hotfix and informed the devs on the mailing list (although the change is probably not worth discussing).

**Comment by ArneBab** [comment]
Thank you! :heart: 

(I can’t be that fast at the moment, so thank you a lot for the hotfix!)
