### ISSUE TITLE
Cleanup of mbtiles seed fails in Mapproxy 1.16

### ISSUE THREAD

**Issue by alfmarcua** [mapproxy/mapproxy#757]
In Mapproxy 1.16 there is a function remove_tile that needs now a parameter call "dimensions". That function is redefined for mbtiles but without that parameter ([https://github.com/mapproxy/mapproxy/blob/1.16.0/mapproxy/cache/mbtiles.py#L374](https://urldefense.com/v3/__https:/github.com/mapproxy/mapproxy/blob/1.16.0/mapproxy/cache/mbtiles.py*L374__;Iw!!DOxrgLBm!HIQ9pLH-JGk0jMZIHxO13nKRwwToADeRfkXeib4LJDQVtxx0Rd27AY1be2IIVLT0D0DuO94a_ochNqHG1h0-tY20KeqVShGbAq8$)) which leads to an error.

## Context

After running a cleanup to remove old tiles, the following error raised:

```
========== Cleanup tasks ==========

Start cleanup process (1 task)

  layer_seed:

    Cleaning up cache 'layer' with grid 'EPSG3857' in EPSG:3857

    Limited to coverage in: -33.75000, 27.05913, 47.81250, 80.17871 (EPSG:4326)

    Levels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

    Remove: tiles older than 2023-10-06 14:56:12.732830

[14:56:12]  0   0.00% -3757032.81427, 3130860.70551, 5322463.15355, 15654303.06896 (0 tiles)

Process TileCleanupWorker-1:

Process TileCleanupWorker-2:

Traceback (most recent call last):

  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap

    self.run()

  File "/opt/data/mapproxy/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 143, in run

    self.work_loop()

  File "/opt/data/mapproxy/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 167, in work_loop

    self.tile_mgr.remove_tile_coords(tiles)

  File "/opt/data/mapproxy/lib/python3.10/site-packages/mapproxy/cache/tile.py", line 204, in remove_tile_coords

    self.cache.remove_tiles(tiles)

  File "/opt/data/mapproxy/lib/python3.10/site-packages/mapproxy/cache/base.py", line 70, in remove_tiles

    self.remove_tile(tile, dimensions=dimensions)

TypeError: MBTilesLevelCache.remove_tile() got an unexpected keyword argument 'dimensions'

Traceback (most recent call last):

  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap

    self.run()

  File "/opt/data/mapproxy/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 143, in run

    self.work_loop()

  File "/opt/data/mapproxy/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 167, in work_loop

    self.tile_mgr.remove_tile_coords(tiles)

  File "/opt/data/mapproxy/lib/python3.10/site-packages/mapproxy/cache/tile.py", line 204, in remove_tile_coords

    self.cache.remove_tiles(tiles)

  File "/opt/data/mapproxy/lib/python3.10/site-packages/mapproxy/cache/base.py", line 70, in remove_tiles

    self.remove_tile(tile, dimensions=dimensions)

TypeError: MBTilesLevelCache.remove_tile() got an unexpected keyword argument 'dimensions'

[2023-10-06 14:56:17,747] mapproxy.seed.seeder - WARNING - no workers left, stopping
```

## Expected Behavior

Perform cleanup of mbtiles to remove old tiles.

## Actual Behavior

Failed.

## Possible Fix

A quick fix is really simple since this parameter can be declared although it won't be used. I will make a PR.

## Steps to Reproduce

1. mapproxy-seed -f mapproxy.yaml -s seed-cleanup.yaml
2. Fails

## Context

After seeding mbtiles some of them need a cleanup.

## Your Environment

* Version used: 1.16
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 3.10.12
* Server type and version: Launched directly through terminal
* Operating System and version: Ubuntu 22.04

**Comment by weskamm** [comment]
should be fixed by https://github.com/mapproxy/mapproxy/pull/758
