### ISSUE TITLE
mapproxy-seed: TypeError: unhashable type: 'dict_keys'

### ISSUE THREAD

**Issue by Tapter** [mapproxy/mapproxy#966]
## Context
When using mapproxy-seed, with mapproxy 2.2, the "grids" property seems to be mandatory now in the seed configuration

## Expected Behavior
I have a working mapproxy.yaml which I can serve using serve-dev without issues.
Additionally a seed.yaml

```
seeds:

  test:
    caches: [test_cache]
    #grids: [GLOBAL_MERCATOR]
    levels:
      from: 8
      to: 10
```

## Actual Behavior
`mapproxy-seed -f conf/mapproxy.yaml -s conf/seed.yaml` throws the following stacktrace:
```
Traceback (most recent call last):
  File "/mnt/d/Maps/mapproxy/virtualenv-mapproxy2/bin/mapproxy-seed", line 8, in <module>
    sys.exit(main())
  File "/mnt/d/Maps/mapproxy/virtualenv-mapproxy2/lib/python3.10/site-packages/mapproxy/seed/script.py", line 366, in main
    return SeedScript()()
  File "/mnt/d/Maps/mapproxy/virtualenv-mapproxy2/lib/python3.10/site-packages/mapproxy/seed/script.py", line 224, in __call__
    seed_tasks = seed_conf.seeds(seed_names)
  File "/mnt/d/Maps/mapproxy/virtualenv-mapproxy2/lib/python3.10/site-packages/mapproxy/seed/config.py", line 207, in seeds
    seed_conf = SeedConfiguration(seed_name, seed_conf, self)
  File "/mnt/d/Maps/mapproxy/virtualenv-mapproxy2/lib/python3.10/site-packages/mapproxy/seed/config.py", line 288, in __init__
    ConfigurationBase.__init__(self, name, conf, seeding_conf)
  File "/mnt/d/Maps/mapproxy/virtualenv-mapproxy2/lib/python3.10/site-packages/mapproxy/seed/config.py", line 236, in __init__
    self.grids = self._grids(self.caches)
  File "/mnt/d/Maps/mapproxy/virtualenv-mapproxy2/lib/python3.10/site-packages/mapproxy/seed/config.py", line 265, in _grids
    for cache_grids in {cache.keys() for cache in caches.values()}:
  File "/mnt/d/Maps/mapproxy/virtualenv-mapproxy2/lib/python3.10/site-packages/mapproxy/seed/config.py", line 265, in <setcomp>
    for cache_grids in {cache.keys() for cache in caches.values()}:
```

## Possible Fix
uncomment the grids property. However, this wasn't necessary with 1.6.0 and the documentation still says: "By default, the grids that are common to all configured caches will be seeded." (and my cache also only has the GLOBAL_MERCATOR grid).

## Your Environment
* Version used: 2.2.0
* Python 3.10.12
* Operating System and version: Ubuntu 22.04

**Comment by weskamm** [comment]
confirmed, can be replicated with default auto generated mapproxy.yaml / seed.yaml
